services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64 # 플랫폼을 amd64로 설정
    container_name: nestjs_app
    env_file:
      - .env.production # 실행 시점에 사용할 환경 변수 주입
    depends_on:
      - redis
      - mysql
    ports:
      - 80:3000
    volumes:
      - ./logs:/usr/src/app/logs
    command: >
      sh -c "
      dockerize -wait tcp://mysql:3306 -timeout 30s &&
      sleep 10 &&
      npm run start:prod 
      "
    

  redis:
    image: redis:7
    platform: linux/amd64 # 플랫폼을 amd64로 설정
    container_name: redis
    command: ["redis-server"]
    ports:
      - 3000:6379

  
  mysql:
    image: mysql:5.7
    platform: linux/amd64 # 플랫폼을 amd64로 설정
    container_name: mysql
    ports:
      - 8080:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./wsdapp_backup.sql:/docker-entrypoint-initdb.d/wsdapp_backup.sql
    environment:
      - MYSQL_DATABASE=wsd_db
      - MYSQL_ROOT_PASSWORD=wsdpass
