
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: # .env에서 값을 가져와 build-arg로 전달
        DATABASE_URL: ${DATABASE_URL}
    platform: linux/amd64 # 플랫폼을 amd64로 설정
    container_name: nestjs_app
    env_file:
      - .env.production # 실행 시점에 사용할 환경 변수 주입
    depends_on:
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:7
    platform: linux/amd64 # 플랫폼을 amd64로 설정
    container_name: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
